Repository FRONTENDSCHOOL8/pocket-karly, pull requests merged in 2024-01, with the labels that each got.

#71 Main 브랜치와 develop 브랜치 동기화
  .env
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  index.html
  package-lock.json
  package.json
Labels: Bug, Chore

#83 [Chore] assets 폴더 내 svg 이미지 변경
  src/assets/svg/_sprite.svg
  src/assets/svg/goToTop.svg
  src/assets/svg/menuIcon.svg
Labels: Chore

#84 [Chore] tailwind config 추가
  tailwind.config.js
Labels: Chore

#85 [Docs] - [ ] config 파일 변경 항목 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#87 [Feat] popup 기능 추가
  main.js
  src/js/popup.js
  src/pages/components/popup.html
  vite.config.js
Labels: JS, 🔴Priority: High

#88 [Feat] footer 추가
  src/pages/components/footer.html
  src/styles/footer.css
  src/styles/tailwind.css
Labels: 🔴Priority: High, Feature

#90 [Design] 버튼 공통 스타일 button.css 추가
  src/pages/components/footer.html
  src/styles/button.css
  src/styles/footer.css
  src/styles/tailwind.css
Labels: Tailwind, 🔴Priority: High, Feature

#91 [Feat] 헤더 추가
  public/icons/_sprite.svg
  public/logo.svg
  src/assets/svg/_sprite.svg
  src/assets/svg/down.svg
  src/assets/svg/hamburger-black.svg
  src/pages/components/header.html
  src/pages/components/header.js
  tailwind.config.js
Labels: 🔴Priority: High, Feature

#92 [Feat] register 마크업 및 디자인 추가
  src/assets/svg/_sprite.svg
  src/assets/svg/check.svg
  src/pages/register/index.html
  src/pages/register/register.css
  src/pages/register/register.js
  src/styles/tailwind.css
  vite.config.js
Labels: Help, Feature, Chore

#93 [Feature] add_cart 모달창 제작
  src/js/addCart.js
  src/js/popup.js
  src/pages/components/addCart.html
  src/pages/components/popup.html
  vite.config.js
Labels: 🔴Priority: High, Feature

#95 [Feat] 메인페이지 레이아웃(미완성)
  index.html
  main.js
  package-lock.json
  package.json
  src/assets/svg/arrowReverse.svg
  src/assets/svg/group.svg
  src/styles/tailwind.css
Labels: Feature

#98 [Feat] 회원가입 페이지
  public/icons/_sprite.svg
  src/pages/detail/detail2.css
  src/pages/detail/detail2.js
  src/pages/detail/index2.html
  src/pages/register/index.html
  src/pages/register/register.css
  src/pages/register/register.js
  src/styles/tailwind.css
Labels: Bug, Tailwind, 🔴Priority: High, Feature

#99 [Feat] 메인페이지 완성
  index.html
  main.js
  src/assets/svg/goToTop.svg
Labels: Feature

#100 [Feat] 회원가입 마무리
  src/pages/register/index.html
  src/pages/register/register.js
Labels: Bug, Feature, Database

#102 [Feature] 상품 목록 페이지 구현
  public/icons/_sprite.svg
  src/assets/svg/_sprite.svg
  src/assets/svg/search-gray.svg
  src/pages/productList/index.html
  src/pages/productList/productList.css
  src/pages/productList/productList.js
Labels: 🔴Priority: High, Feature

#107 [Feat] 로그인페이지 구현
  src/pages/login/index.html
  src/pages/login/login.js
  tailwind.config.js
Labels: Feature, Database

#108 [Design] 헤더에 box-shadow 추가
  src/pages/components/header.html
Labels: Tailwind, 🔴Priority: High

#109 [Feat] 회원가입 페이지 완성
  src/pages/components/addressApi.js
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🔴Priority: High, Feature

#111 [Design] input radio, check 수정
  src/pages/register/index.html
  src/pages/register/register.css
Labels: Tailwind, A11Y

#110 [Feat] 로그인페이지
  src/pages/login/index.html
  src/pages/login/login.js
Labels: Feature

#113 [Feat] 회원 탈퇴 기능 추가
  src/pages/components/js/include.js
Labels: 🔴Priority: High, Feature

#115 [Design] 상품리뷰 및 상품문의 마크업 및 디자인
  public/icons/_sprite.svg
  src/assets/svg/_sprite.svg
  src/assets/svg/pageArrow-left.svg
  src/assets/svg/pageArrow-right.svg
  src/pages/detail/detail2.css
  src/pages/detail/index2.html
Labels: Tailwind, HTML, 🔴Priority: High, Chore

#117 [Feat] 메인페이지 swiper에서 상품 DB데이터 불러오기
  index.html
  main.js
  src/pages/components/js/include.js
  src/pages/components/sidebar.html
  src/pages/detail/detail.js
  src/pages/detail/index.html
  vite.config.js
Labels: 🔴Priority: High, Feature

#119 [Feat] 장바구니 페이지 레이아웃 완성 및 기능 추가
  src/pages/cart/cart.js
  src/pages/cart/index.html
  src/styles/tailwind.css
  vite.config.js
Labels: 🔴Priority: High, Feature, Database

#120 [Design] 각 페이지에 header, footer, sidebar include
  index.html
  main.js
  src/pages/cart/cart.js
  src/pages/cart/index.html
  src/pages/components/footer.html
  src/pages/components/js/include.js
  src/pages/components/sidebar.html
  src/pages/detail/detail.js
  src/pages/detail/index.html
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/productList/index.html
  src/pages/productList/productList.js
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🔴Priority: High

#121 [Feat] 장바구니 페이지 체크박스 버튼 기능 추가
  src/pages/cart/index.html
  src/pages/components/addCart.html
Labels: JS, Help, 🔴Priority: High, Feature, Database

#122 [Modify] 메인페이지 크기 조절 및 푸터 수정
  index.html
  src/pages/components/footer.html
Labels: HTML, 🔴Priority: High

#123 [BugFix] 메인페이지 무한루프 버그 수정
  main.js
Labels: Bug

#125 [Refactor] address.js 리팩토링
  .eslintignore
  src/pages/components/addressApi.js
  src/pages/components/js/addressApi.js
Labels: JS, 🟢Priority: Low

#126 [Feat] 상세페이지 하단 구현
  src/pages/detail/detail2.css
  src/pages/detail/detail2.js
  src/pages/detail/index2.html
Labels: Feature

#128 [Feat] 장바구니 기능 추가
  src/pages/cart/cart.js
  src/pages/cart/index.html
Labels: Bug, JS, Help, 🔴Priority: High, Feature

#129 [BugFix] 장바구니 상태변수 관리 수정
  src/pages/cart/cart.js
Labels: JS, 🔴Priority: High, Feature

#132 Feature/detail
  src/assets/images/ex/checkPoint.jpg
  src/assets/images/ex/product.jpg
  src/assets/images/ex/thumb-1.svg
  src/assets/svg/_sprite.svg
  src/assets/svg/false.svg
  src/assets/svg/squre.svg
  src/pages/detail/detail.js
  src/pages/detail/index.html
  src/styles/button.css
  tailwind.config.js
Labels: Feature

#133 [Feat] 회원 장바구니 상품 추가 기능 구현
  src/pages/components/js/addCart.js
Labels: 🔴Priority: High, Feature

#136 [Feat] 상세페이지 하단 기능구현
  public/icons/_sprite.svg
  src/assets/svg/_sprite.svg
  src/assets/svg/thumb.svg
  src/pages/components/js/modal.js
  src/pages/detail/detail2.css
  src/pages/detail/detail2.js
  src/pages/detail/index2.html
Labels: Feature

#137 [Feat] 장바구니 선택한 상품에 맞춰 결제예정금액 출력
  src/pages/cart/cart.js
Labels: 🔴Priority: High, Feature

#141 화면 수정
  src/pages/components/header.html
  src/pages/components/js/include.js
  src/pages/components/sidebar.html
Labels: Bug, Tailwind, HTML

#142 [Feat] 회원 여부/상품 유무에 따른 장바구니 UI 및 기능 분리
  index.html
  src/pages/cart/cart.js
  src/pages/cart/index.html
  src/pages/components/addCart.html
  src/pages/productList/index.html
  src/styles/button.css
Labels: JS, 🔴Priority: High, Feature, Database

#143 [Feat] 상품 상세페이지 카테고리, 브랜드 필터 옆에 카운트 추가
  src/pages/productList/index.html
  src/pages/productList/productList.js
Labels: Feature

#145 [Feat]로그인 시 이전 페이지로 이동
  src/pages/login/login.js
Labels: Feature

#144 [BugFix] 최근본상품 오류 해결
  src/pages/detail/detail.js
Labels: Bug, 🔴Priority: High

#146 [Feat] 장바구니 페이지 배송지 변경 기능 추가
  src/pages/cart/cart.js
  src/pages/components/js/addressApi.js
Labels: JS, 🟡Priority: Medium, Feature

#148 [Modify] 디테일페이지 html, js수정
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: Feature, Database

#149 [Feat] 메인페이지 팝업 기능 추가
  index.html
  main.js
Labels: HTML, JS, 🔴Priority: High, Feature

#150 [BugFix] 최근본상품 오류 해결
  src/pages/detail/detail.js
Labels: Bug

#151 [Feat] 상세페이지 하단 기능 구현
  src/api/defaultAuthData.js
  src/pages/components/js/addressApi.js
  src/pages/detail/detail2.js
  src/pages/detail/index.html
  src/pages/register/index.html
  src/pages/register/register.js
Labels: Feature

#152 [Feat] 상세페이지
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: Feature

#153 [BugFix] 장바구니페이지 비회원 상품삭제 기능 수정
  src/pages/cart/cart.js
  src/pages/cart/index.html
Labels: JS, 🔴Priority: High, Feature, Database

#154 [Feat] 기본 확인 모달 컴포넌트 제작
  src/pages/components/js/modals.js
  src/pages/components/modal.html
Labels: HTML, JS, 🟡Priority: Medium, Feature

#159 [Feat] 장바구니페이지 모달 컴포넌트 적용
  src/pages/cart/cart.js
  src/pages/cart/index.html
  src/pages/components/js/modals.js
  src/pages/components/modal.html
Labels: HTML, JS, 🟡Priority: Medium, Feature

#161 [Bug] sort 기능 버그발생
  src/pages/detail/detail2.js
  src/pages/detail/index.html
Labels: Bug

#162 [bugFix] 상세페이지 sort 버그 수정
  src/pages/detail/detail2.js
  src/pages/detail/index.html
Labels: Feature

#163 [Feat] 메인 스와이퍼, 상세 페이지
  main.js
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: Feature

#166 [Modify] 장바구니 페이지 버튼 기능 수정
  index.html
  public/icons/_sprite.svg
  src/assets/svg/_sprite.svg
  src/assets/svg/menuIcon.svg
  src/pages/cart/cart.js
Labels: 🟡Priority: Medium, Feature, Chore

#169 [Feat] 메인, 상세페이지
  main.js
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: Feature

#170 [Feat] 도움돼요 구현 시도
  src/pages/detail/detail2.js
  src/pages/detail/index.html
  src/pages/register/register.js
Labels: Feature

#171 [Feat] 상세페이지
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: Feature

#176 [BugFix] 리뷰 선택버튼 버그
  src/pages/detail/detail2.js
  src/pages/detail/index.html
Labels: Bug

#177 [Bugfix] 장바구니페이지 수량변경 버튼 오류 수정
  src/pages/cart/cart.js
Labels: 🔴Priority: High

#178 [BugFix] 상품 목록 페이지 정렬 수정
  src/pages/components/js/include.js
  src/pages/productList/productList.js
Labels: Bug

#179 [Modify] 상세페이지
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: Feature

#180 [Modify] 회원가입/로그인 alert 커스텀
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🟢Priority: Low

#181 [Modify] 회원가입페이지 모달 추가
  src/pages/register/index.html
Labels: 🟢Priority: Low

#182 [Modify] 상품 상세페이지 alert 커스텀
  src/pages/detail/detail.js
  src/pages/detail/detail2.js
  src/pages/detail/index.html
  src/pages/register/register.js
Labels: 🟢Priority: Low

#183 [BugFix] 상품 상세페이지 탭 메뉴 스크롤 이동 오류 수정
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: 🟡Priority: Medium

#185 [BugFix] 리뷰 section id 수정
  README.md
  src/pages/detail/detail2.js
  src/pages/detail/index.html
Labels: Bug
